### ISSUE TITLE
Reject record updates (PUT) when timestamp outdated

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-server#155]
When a record is updated the client will pass the date of the latest modification in "updated_at" at the time of last download. If the record on the server has a newer timestamp (as a result of someone else updating it since the last download), the server should reject the PUT request with an error.

**Comment by barancw** [comment]
Going to use a activerecord validation and check the updated_at field.  It must be added as a permitted parameter.

**Comment by tmfrnz** [comment]
@barancw, please also add to users_controller

**Comment by barancw** [comment]
This can not be added to users because of the devise token updates.  It will always be out of date after 1 new request.

**Comment by tmfrnz** [comment]
for users table see #190
