### ISSUE TITLE
User associates one or more actions with a single recommendation

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#26]
As a User

I want to associate one or more actions with a recommendation

So that I can track progress on the recommendation

---

Development tasks:
1. Add many-to-many relationship between recommendations and actions
2. Add filtered list widget to handle action selection
3. Saving the recommendation updates the associated actions

<img width="856" alt="screenshot 2016-08-08 15 47 50" src="https://cloud.githubusercontent.com/assets/292020/17468796/80bd4fbc-5d7f-11e6-8313-207f192c9da7.png">

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#21
