### ISSUE TITLE
User associates one or more recommendations with a single action

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#27]
As a user

I want to associate one or more recommendations with an action

So that I can track progress of the recommendation

---

Development tasks:
1. Re-use recommendation-action association from Issue #26
2. Add list widget for filtering and selecting recommendations
3. List widget has filters for recommendations as per wireframes
4. When the association list is not in edit mode, a list of recommendations is shown as per the recommendation list page (see wireframes)
5. Saving the action persists the selected recommendations

<img width="916" alt="screenshot 2016-08-09 10 07 23" src="https://cloud.githubusercontent.com/assets/292020/17498075/33d3491e-5e19-11e6-9c59-77d56f04ce58.png">

<img width="896" alt="screenshot 2016-08-09 10 08 29" src="https://cloud.githubusercontent.com/assets/292020/17498079/3ee08358-5e19-11e6-9f79-034a89c48520.png">

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#22
