### ISSUE TITLE
Advanced filterable multiselect list widget (recommendations, actions)

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#28]
As a user of Sadata

I want an easy to use UI element for filtering a large list of things by keyword and associated categories and choosing one or more options from the list.

---

Development tasks:
1. Implement partial structure for rendering list container
2. Implement generic-ish Javascript to perform XHR requests to populate the list
3. Allow filtering of the list using a search field
4. Consider supporting pagination
5. Support adding new record and selecting it from the list
6. If items are pre-selected, show them at the top of the list
7. Try not to put too much magic in

<img width="927" alt="screenshot 2016-08-08 16 05 13" src="https://cloud.githubusercontent.com/assets/292020/17469082/f9617eb4-5d81-11e6-8f4a-f765f0e7f277.png">

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#23
