### ISSUE TITLE
User creates category for taxonomy

### ISSUE THREAD

**Issue by ben-rabid** [dumparkltd/hr-nmrf-server#29]
As a user

I want to create a category for each Taxonomy

So that I can assign them to Recommendations (#44) and Actions (#45)

---

Development Tasks:
1. Generate Category Model
2. Set up Category Model for i18n
3. Add title attribute to model
4. Saving takes the user to the list of categories
6. Failure to save shows form errors
7. Successful save shows a success message

---

Considerations:
A user can only access this page via a Taxonomy items list
A user implicitly links this Category to the Taxonomy items

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#24
