### ISSUE TITLE
Developer creates Taxonomies

### ISSUE THREAD

**Issue by ben-rabid** [dumparkltd/hr-nmrf-server#30]
As a developer

I want to create Taxonomies

So that users can add categories to taxonomy and associate categories with Recommendations or Actions

---

Development Tasks:
1. Generate Taxonomy model
2. Add i18n to taxonomy labels
3. Create database seed with base taxonomies: Human Rights Body, Session, Right, Affected Persons, Thematic Cluster, Agency

**Comment by tmfrnz** [comment]
delivered in https://github.com/dumparkltd/hr-nmrf-server/pull/146 through https://github.com/dumparkltd/hr-nmrf-server/commit/6fb8788a356f4fc8e61e6c60337bed3754fd2f03
