### ISSUE TITLE
User 'quick views' actions from recommendation list

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#34]
As a user

I want to quickly see a summary of the actions associated with a recommendation from the list page

So that I don't have to jump into each recommendation page to see the actions.

---

Development tasks:
1. Implement action list bound to the action count label on the recommendations list page
2.  Ensure hover is friendly - e.g. don't just bind the hiding of the box when the cursor leaves the icon, allow the user to scroll over the action list.
3. UI implemented as per wireframes

![screenshot 2016-08-09 08 44 00](https://cloud.githubusercontent.com/assets/292020/17495557/98994abc-5e0d-11e6-9eb0-6c2625f61770.png)

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#27
