### ISSUE TITLE
User views list of categories for a taxonomy

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#36]
As a User

I want to see a list of all categories for each taxonomy

So that I can see the categories available 

---

Development tasks:
1. Display unfiltered list of categories
2. Category shows title and count of associated records (split into types if practical)
3. Show link to add new category
4. Each category can be edited 
5. Edit form implemented as per wireframes

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#29
