### ISSUE TITLE
User groups list items by category/taxonomy

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#38]
As a User

I want to ~~sort~~ _group_ recommendations _by category_

So that I can find a set of recommendations I am looking for

Development tasks:
1. Sort by ~~title~~ _category_
2. Other ~~sorts~~ _(eg by associated  category)_ TBC

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#30
