### ISSUE TITLE
User can reset password

### ISSUE THREAD

**Issue by joshmcarthur** [dumparkltd/hr-nmrf-server#7]
As an agency user

I want to reset my password when I have forgotten it

So that I can log in

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#3

**Comment by tmfrnz** [comment]
the following email is being sent
```
Hello timo@dumpark.com!

Someone has requested a link to change your password. You can do this through the link below.

Change my password (https://undp-sadata-staging.herokuapp.com/auth/password/edit?reset_password_token=YhJWKTJSU5nQxsY78-zN)

If you didn't request this, please ignore this email.

Your password won't change until you access the link above and create a new one.
```
from
`please-change-me-at-config-initializers-devise@example.com`

**Comment by tmfrnz** [comment]
the reset link 
https://undp-sadata-staging.herokuapp.com/auth/password/edit?reset_password_token=YhJWKTJSU5nQxsY78-zN
results in a page not found error

**Comment by tmfrnz** [comment]
@barancw should this be a link to a client side URL or should we simply open the server side endpoint for the password reset?

**Comment by tmfrnz** [comment]
endpoint:
POST /auth/password/

payload
```
{
email: email-address,
redirect_url: redirect_url
}
```

**Comment by barancw** [comment]
Populate redirect_url with the URL of the frontend page that will have the form that has password and password_confirmation.  It will get query string data:

client_id:yJ0VoOb5GyDhpZCej6jB9g
config:default
expiry:1495872339
reset_password:true
token:1d50Ef8nVV9nM9qapHoX_w
uid:chris@baran.co.nz

This needs to be send in the headers (as the other requests do)
You will do a PUT to /auth/password with the payload of password and password_confirmation with the headers set and it should work.
