### ISSUE TITLE
User uploads document for progress report

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-server#73]

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#52

**Comment by tmfrnz** [comment]
@tmfrnz to consider options for uploading files directly from client to AWS S3

**Comment by tmfrnz** [comment]
will mainly handle client-side but will want server-side authorisation via endpoint eg https://github.com/odysseyscience/react-s3-uploader#ruby-on-rails-assuming-fog-usage

**Comment by tmfrnz** [comment]
@barancw will need to add the bucket region to fog config to make it work with any region. default setup only appears to work with standard region (US east)
https://github.com/dumparkltd/hr-nmrf-server/blob/master/config/initializers/fog.rb
::FogStorage = Fog::Storage.new(
  provider: 'AWS',
  aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  region: ENV['AWS_BUCKET_REGION']
)

**Comment by barancw** [comment]
@tmfrnz: The build is in progress.  I set the region to Asia Pacific (Sydney)	ap-southeast-2.  You can change it at: https://dashboard.heroku.com/apps/undp-sadata-staging/settings in the config vars.

**Comment by tmfrnz** [comment]
thanks @barancw!

**Comment by tmfrnz** [comment]
@barancw confirming that this is working now
